//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("MeublatexDataModel", "FK_image_image", "image", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MvcMeublatexApp.Models.image), "image1", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(MvcMeublatexApp.Models.image), true)]
[assembly: EdmRelationshipAttribute("MeublatexDataModel", "FK_Produit_image", "image", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(MvcMeublatexApp.Models.image), "Produit", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MvcMeublatexApp.Models.Produit), true)]
[assembly: EdmRelationshipAttribute("MeublatexDataModel", "FK_Client_Commande", "Commande", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(MvcMeublatexApp.Models.Commande), "Client", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MvcMeublatexApp.Models.Client), true)]
[assembly: EdmRelationshipAttribute("MeublatexDataModel", "FK_Commande_Commande", "Commande", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MvcMeublatexApp.Models.Commande), "Commande1", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(MvcMeublatexApp.Models.Commande), true)]
[assembly: EdmRelationshipAttribute("MeublatexDataModel", "FK_Commande_Produit", "Produit", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(MvcMeublatexApp.Models.Produit), "Commande", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MvcMeublatexApp.Models.Commande), true)]

#endregion

namespace MvcMeublatexApp.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class MeublatexDataEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new MeublatexDataEntities object using the connection string found in the 'MeublatexDataEntities' section of the application configuration file.
        /// </summary>
        public MeublatexDataEntities() : base("name=MeublatexDataEntities", "MeublatexDataEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MeublatexDataEntities object.
        /// </summary>
        public MeublatexDataEntities(string connectionString) : base(connectionString, "MeublatexDataEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MeublatexDataEntities object.
        /// </summary>
        public MeublatexDataEntities(EntityConnection connection) : base(connection, "MeublatexDataEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Client> Client
        {
            get
            {
                if ((_Client == null))
                {
                    _Client = base.CreateObjectSet<Client>("Client");
                }
                return _Client;
            }
        }
        private ObjectSet<Client> _Client;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<image> image
        {
            get
            {
                if ((_image == null))
                {
                    _image = base.CreateObjectSet<image>("image");
                }
                return _image;
            }
        }
        private ObjectSet<image> _image;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Produit> Produit
        {
            get
            {
                if ((_Produit == null))
                {
                    _Produit = base.CreateObjectSet<Produit>("Produit");
                }
                return _Produit;
            }
        }
        private ObjectSet<Produit> _Produit;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Commande> Commande
        {
            get
            {
                if ((_Commande == null))
                {
                    _Commande = base.CreateObjectSet<Commande>("Commande");
                }
                return _Commande;
            }
        }
        private ObjectSet<Commande> _Commande;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Client EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToClient(Client client)
        {
            base.AddObject("Client", client);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the image EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToimage(image image)
        {
            base.AddObject("image", image);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Produit EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProduit(Produit produit)
        {
            base.AddObject("Produit", produit);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Commande EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCommande(Commande commande)
        {
            base.AddObject("Commande", commande);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MeublatexDataModel", Name="Client")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Client : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Client object.
        /// </summary>
        /// <param name="id_clt">Initial value of the Id_clt property.</param>
        /// <param name="nom_clt">Initial value of the Nom_clt property.</param>
        /// <param name="prenom_clt">Initial value of the Prenom_clt property.</param>
        /// <param name="e_mail">Initial value of the E_mail property.</param>
        public static Client CreateClient(global::System.Int32 id_clt, global::System.String nom_clt, global::System.String prenom_clt, global::System.String e_mail)
        {
            Client client = new Client();
            client.Id_clt = id_clt;
            client.Nom_clt = nom_clt;
            client.Prenom_clt = prenom_clt;
            client.E_mail = e_mail;
            return client;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id_clt
        {
            get
            {
                return _Id_clt;
            }
            set
            {
                if (_Id_clt != value)
                {
                    OnId_cltChanging(value);
                    ReportPropertyChanging("Id_clt");
                    _Id_clt = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id_clt");
                    OnId_cltChanged();
                }
            }
        }
        private global::System.Int32 _Id_clt;
        partial void OnId_cltChanging(global::System.Int32 value);
        partial void OnId_cltChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nom_clt
        {
            get
            {
                return _Nom_clt;
            }
            set
            {
                OnNom_cltChanging(value);
                ReportPropertyChanging("Nom_clt");
                _Nom_clt = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nom_clt");
                OnNom_cltChanged();
            }
        }
        private global::System.String _Nom_clt;
        partial void OnNom_cltChanging(global::System.String value);
        partial void OnNom_cltChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Prenom_clt
        {
            get
            {
                return _Prenom_clt;
            }
            set
            {
                OnPrenom_cltChanging(value);
                ReportPropertyChanging("Prenom_clt");
                _Prenom_clt = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Prenom_clt");
                OnPrenom_cltChanged();
            }
        }
        private global::System.String _Prenom_clt;
        partial void OnPrenom_cltChanging(global::System.String value);
        partial void OnPrenom_cltChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String E_mail
        {
            get
            {
                return _E_mail;
            }
            set
            {
                OnE_mailChanging(value);
                ReportPropertyChanging("E_mail");
                _E_mail = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("E_mail");
                OnE_mailChanged();
            }
        }
        private global::System.String _E_mail;
        partial void OnE_mailChanging(global::System.String value);
        partial void OnE_mailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Id_cmd
        {
            get
            {
                return _Id_cmd;
            }
            set
            {
                OnId_cmdChanging(value);
                ReportPropertyChanging("Id_cmd");
                _Id_cmd = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Id_cmd");
                OnId_cmdChanged();
            }
        }
        private Nullable<global::System.Int32> _Id_cmd;
        partial void OnId_cmdChanging(Nullable<global::System.Int32> value);
        partial void OnId_cmdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MeublatexDataModel", "FK_Client_Commande", "Commande")]
        public Commande Commande
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Commande>("MeublatexDataModel.FK_Client_Commande", "Commande").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Commande>("MeublatexDataModel.FK_Client_Commande", "Commande").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Commande> CommandeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Commande>("MeublatexDataModel.FK_Client_Commande", "Commande");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Commande>("MeublatexDataModel.FK_Client_Commande", "Commande", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MeublatexDataModel", Name="Commande")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Commande : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Commande object.
        /// </summary>
        /// <param name="id_cmd">Initial value of the Id_cmd property.</param>
        public static Commande CreateCommande(global::System.Int32 id_cmd)
        {
            Commande commande = new Commande();
            commande.Id_cmd = id_cmd;
            return commande;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id_cmd
        {
            get
            {
                return _Id_cmd;
            }
            set
            {
                if (_Id_cmd != value)
                {
                    OnId_cmdChanging(value);
                    ReportPropertyChanging("Id_cmd");
                    _Id_cmd = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id_cmd");
                    OnId_cmdChanged();
                }
            }
        }
        private global::System.Int32 _Id_cmd;
        partial void OnId_cmdChanging(global::System.Int32 value);
        partial void OnId_cmdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Libelle_cmd
        {
            get
            {
                return _Libelle_cmd;
            }
            set
            {
                OnLibelle_cmdChanging(value);
                ReportPropertyChanging("Libelle_cmd");
                _Libelle_cmd = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Libelle_cmd");
                OnLibelle_cmdChanged();
            }
        }
        private global::System.String _Libelle_cmd;
        partial void OnLibelle_cmdChanging(global::System.String value);
        partial void OnLibelle_cmdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> qtit
        {
            get
            {
                return _qtit;
            }
            set
            {
                OnqtitChanging(value);
                ReportPropertyChanging("qtit");
                _qtit = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("qtit");
                OnqtitChanged();
            }
        }
        private Nullable<global::System.Int32> _qtit;
        partial void OnqtitChanging(Nullable<global::System.Int32> value);
        partial void OnqtitChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Id_prod
        {
            get
            {
                return _Id_prod;
            }
            set
            {
                OnId_prodChanging(value);
                ReportPropertyChanging("Id_prod");
                _Id_prod = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Id_prod");
                OnId_prodChanged();
            }
        }
        private Nullable<global::System.Int32> _Id_prod;
        partial void OnId_prodChanging(Nullable<global::System.Int32> value);
        partial void OnId_prodChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Prix_total
        {
            get
            {
                return _Prix_total;
            }
            set
            {
                OnPrix_totalChanging(value);
                ReportPropertyChanging("Prix_total");
                _Prix_total = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Prix_total");
                OnPrix_totalChanged();
            }
        }
        private Nullable<global::System.Int32> _Prix_total;
        partial void OnPrix_totalChanging(Nullable<global::System.Int32> value);
        partial void OnPrix_totalChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MeublatexDataModel", "FK_Client_Commande", "Client")]
        public EntityCollection<Client> Client
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Client>("MeublatexDataModel.FK_Client_Commande", "Client");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Client>("MeublatexDataModel.FK_Client_Commande", "Client", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MeublatexDataModel", "FK_Commande_Commande", "Commande1")]
        public Commande Commande1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Commande>("MeublatexDataModel.FK_Commande_Commande", "Commande1").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Commande>("MeublatexDataModel.FK_Commande_Commande", "Commande1").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Commande> Commande1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Commande>("MeublatexDataModel.FK_Commande_Commande", "Commande1");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Commande>("MeublatexDataModel.FK_Commande_Commande", "Commande1", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MeublatexDataModel", "FK_Commande_Commande", "Commande")]
        public Commande Commande2
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Commande>("MeublatexDataModel.FK_Commande_Commande", "Commande").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Commande>("MeublatexDataModel.FK_Commande_Commande", "Commande").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Commande> Commande2Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Commande>("MeublatexDataModel.FK_Commande_Commande", "Commande");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Commande>("MeublatexDataModel.FK_Commande_Commande", "Commande", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MeublatexDataModel", "FK_Commande_Produit", "Produit")]
        public Produit Produit
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Produit>("MeublatexDataModel.FK_Commande_Produit", "Produit").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Produit>("MeublatexDataModel.FK_Commande_Produit", "Produit").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Produit> ProduitReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Produit>("MeublatexDataModel.FK_Commande_Produit", "Produit");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Produit>("MeublatexDataModel.FK_Commande_Produit", "Produit", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MeublatexDataModel", Name="image")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class image : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new image object.
        /// </summary>
        /// <param name="img_id">Initial value of the img_id property.</param>
        /// <param name="img_name">Initial value of the img_name property.</param>
        /// <param name="img">Initial value of the img property.</param>
        public static image Createimage(global::System.Int32 img_id, global::System.String img_name, global::System.Byte[] img)
        {
            image image = new image();
            image.img_id = img_id;
            image.img_name = img_name;
            image.img = img;
            return image;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 img_id
        {
            get
            {
                return _img_id;
            }
            set
            {
                if (_img_id != value)
                {
                    Onimg_idChanging(value);
                    ReportPropertyChanging("img_id");
                    _img_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("img_id");
                    Onimg_idChanged();
                }
            }
        }
        private global::System.Int32 _img_id;
        partial void Onimg_idChanging(global::System.Int32 value);
        partial void Onimg_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String img_name
        {
            get
            {
                return _img_name;
            }
            set
            {
                Onimg_nameChanging(value);
                ReportPropertyChanging("img_name");
                _img_name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("img_name");
                Onimg_nameChanged();
            }
        }
        private global::System.String _img_name;
        partial void Onimg_nameChanging(global::System.String value);
        partial void Onimg_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] img
        {
            get
            {
                return StructuralObject.GetValidValue(_img);
            }
            set
            {
                OnimgChanging(value);
                ReportPropertyChanging("img");
                _img = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("img");
                OnimgChanged();
            }
        }
        private global::System.Byte[] _img;
        partial void OnimgChanging(global::System.Byte[] value);
        partial void OnimgChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MeublatexDataModel", "FK_image_image", "image1")]
        public image image1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<image>("MeublatexDataModel.FK_image_image", "image1").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<image>("MeublatexDataModel.FK_image_image", "image1").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<image> image1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<image>("MeublatexDataModel.FK_image_image", "image1");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<image>("MeublatexDataModel.FK_image_image", "image1", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MeublatexDataModel", "FK_image_image", "image")]
        public image image2
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<image>("MeublatexDataModel.FK_image_image", "image").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<image>("MeublatexDataModel.FK_image_image", "image").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<image> image2Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<image>("MeublatexDataModel.FK_image_image", "image");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<image>("MeublatexDataModel.FK_image_image", "image", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MeublatexDataModel", "FK_Produit_image", "Produit")]
        public EntityCollection<Produit> Produit
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Produit>("MeublatexDataModel.FK_Produit_image", "Produit");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Produit>("MeublatexDataModel.FK_Produit_image", "Produit", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MeublatexDataModel", Name="Produit")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Produit : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Produit object.
        /// </summary>
        /// <param name="id_prod">Initial value of the Id_prod property.</param>
        /// <param name="categorie">Initial value of the categorie property.</param>
        /// <param name="qtit_stock">Initial value of the qtit_stock property.</param>
        /// <param name="qtit_vendu">Initial value of the qtit_vendu property.</param>
        /// <param name="prix">Initial value of the Prix property.</param>
        public static Produit CreateProduit(global::System.Int32 id_prod, global::System.String categorie, global::System.Int32 qtit_stock, global::System.Int32 qtit_vendu, global::System.Int32 prix)
        {
            Produit produit = new Produit();
            produit.Id_prod = id_prod;
            produit.categorie = categorie;
            produit.qtit_stock = qtit_stock;
            produit.qtit_vendu = qtit_vendu;
            produit.Prix = prix;
            return produit;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id_prod
        {
            get
            {
                return _Id_prod;
            }
            set
            {
                if (_Id_prod != value)
                {
                    OnId_prodChanging(value);
                    ReportPropertyChanging("Id_prod");
                    _Id_prod = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id_prod");
                    OnId_prodChanged();
                }
            }
        }
        private global::System.Int32 _Id_prod;
        partial void OnId_prodChanging(global::System.Int32 value);
        partial void OnId_prodChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String categorie
        {
            get
            {
                return _categorie;
            }
            set
            {
                OncategorieChanging(value);
                ReportPropertyChanging("categorie");
                _categorie = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("categorie");
                OncategorieChanged();
            }
        }
        private global::System.String _categorie;
        partial void OncategorieChanging(global::System.String value);
        partial void OncategorieChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 qtit_stock
        {
            get
            {
                return _qtit_stock;
            }
            set
            {
                Onqtit_stockChanging(value);
                ReportPropertyChanging("qtit_stock");
                _qtit_stock = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("qtit_stock");
                Onqtit_stockChanged();
            }
        }
        private global::System.Int32 _qtit_stock;
        partial void Onqtit_stockChanging(global::System.Int32 value);
        partial void Onqtit_stockChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 qtit_vendu
        {
            get
            {
                return _qtit_vendu;
            }
            set
            {
                Onqtit_venduChanging(value);
                ReportPropertyChanging("qtit_vendu");
                _qtit_vendu = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("qtit_vendu");
                Onqtit_venduChanged();
            }
        }
        private global::System.Int32 _qtit_vendu;
        partial void Onqtit_venduChanging(global::System.Int32 value);
        partial void Onqtit_venduChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Prix
        {
            get
            {
                return _Prix;
            }
            set
            {
                OnPrixChanging(value);
                ReportPropertyChanging("Prix");
                _Prix = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Prix");
                OnPrixChanged();
            }
        }
        private global::System.Int32 _Prix;
        partial void OnPrixChanging(global::System.Int32 value);
        partial void OnPrixChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> id_img
        {
            get
            {
                return _id_img;
            }
            set
            {
                Onid_imgChanging(value);
                ReportPropertyChanging("id_img");
                _id_img = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_img");
                Onid_imgChanged();
            }
        }
        private Nullable<global::System.Int32> _id_img;
        partial void Onid_imgChanging(Nullable<global::System.Int32> value);
        partial void Onid_imgChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MeublatexDataModel", "FK_Produit_image", "image")]
        public image image
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<image>("MeublatexDataModel.FK_Produit_image", "image").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<image>("MeublatexDataModel.FK_Produit_image", "image").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<image> imageReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<image>("MeublatexDataModel.FK_Produit_image", "image");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<image>("MeublatexDataModel.FK_Produit_image", "image", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MeublatexDataModel", "FK_Commande_Produit", "Commande")]
        public EntityCollection<Commande> Commande
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Commande>("MeublatexDataModel.FK_Commande_Produit", "Commande");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Commande>("MeublatexDataModel.FK_Commande_Produit", "Commande", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
